package view;

import java.util.ArrayList;
import model.CamposTabela;
import model.Gerenciador;

/**
 *
 * @author Bruno, Douglas e Tamires
 */
public class ExibirTabela extends javax.swing.JFrame {

    private static Gerenciador gerenciador;

    /**
     * Creates new form ExibirTabela
     */
    public ExibirTabela(Gerenciador gerenciador) {
        initComponents();
        this.gerenciador = gerenciador;
        mostrarTabela();
    }

    public void mostrarTabela() {
            ArrayList<CamposTabela> lista = gerenciador.getLista();
            String saida = "";
            for (CamposTabela ct : lista) {
                saida += ct.toString() + "\n";
                //System.out.println(ct.toString());
            }
            jSaidaConsole.setText(saida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaidaConsole = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSaidaConsole = new javax.swing.JTextArea();
        jLabelIPDestino = new javax.swing.JLabel();
        jLabelMetrica = new javax.swing.JLabel();
        jLabelSaida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela de Roteamento");

        jLabelSaidaConsole.setText("Saída Console: Tabela de Roteamento");

        jSaidaConsole.setColumns(20);
        jSaidaConsole.setRows(5);
        jScrollPane1.setViewportView(jSaidaConsole);

        jLabelIPDestino.setText("IP Destino");

        jLabelMetrica.setText("Métrica");

        jLabelSaida.setText("Saída");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSaidaConsole)
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIPDestino)
                        .addGap(118, 118, 118)
                        .addComponent(jLabelMetrica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jLabelSaida)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaidaConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIPDestino)
                    .addComponent(jLabelMetrica)
                    .addComponent(jLabelSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirTabela(gerenciador).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelIPDestino;
    private javax.swing.JLabel jLabelMetrica;
    private javax.swing.JLabel jLabelSaida;
    private javax.swing.JLabel jLabelSaidaConsole;
    private javax.swing.JTextArea jSaidaConsole;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
