package view;

import model.Client;
import model.Gerenciador;
import model.Server;

/**
 *
 * @author Bruno, Douglas e Tamires
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Gerenciador gerenciador;
    Server serv;
    Client cli;

    public Principal() {
        initComponents();

        gerenciador = new Gerenciador();
        serv = gerenciador.atualServer();
        cli = gerenciador.atualCliente();
        
        Thread thCli = new Thread(cli);
        Thread thServ = new Thread(serv);
        Thread thMenu = new Thread(gerenciador);
        
        thCli.start();
        thServ.start();
        thMenu.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AdicionarMaquinas = new javax.swing.JMenuItem();
        AdicionarIpGrupo = new javax.swing.JMenuItem();
        MostrarRoteamento = new javax.swing.JMenuItem();
        RemoveIps = new javax.swing.JMenuItem();
        Fechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Roteamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        AdicionarMaquinas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AdicionarMaquinas.setText("Adicionar Máquina");
        AdicionarMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarMaquinasActionPerformed(evt);
            }
        });
        jMenu1.add(AdicionarMaquinas);

        AdicionarIpGrupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        AdicionarIpGrupo.setText("Adicionar IP Grupo");
        AdicionarIpGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarIpGrupoActionPerformed(evt);
            }
        });
        jMenu1.add(AdicionarIpGrupo);

        MostrarRoteamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        MostrarRoteamento.setText("Mostra IPs Roteados");
        MostrarRoteamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarRoteamentoActionPerformed(evt);
            }
        });
        jMenu1.add(MostrarRoteamento);

        RemoveIps.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        RemoveIps.setText("Remover IP");
        RemoveIps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveIpsActionPerformed(evt);
            }
        });
        jMenu1.add(RemoveIps);

        Fechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        jMenu1.add(Fechar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarMaquinasActionPerformed
        AdicionaIp maquina = new AdicionaIp(gerenciador);
        maquina.setVisible(true);
    }//GEN-LAST:event_AdicionarMaquinasActionPerformed

    private void AdicionarIpGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarIpGrupoActionPerformed
        AdicionaGrupo grupo = new AdicionaGrupo(gerenciador);
        grupo.setVisible(true);
    }//GEN-LAST:event_AdicionarIpGrupoActionPerformed

    private void MostrarRoteamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarRoteamentoActionPerformed
        ExibirTabela exibe = new ExibirTabela(gerenciador);
        exibe.setVisible(true);
    }//GEN-LAST:event_MostrarRoteamentoActionPerformed

    private void RemoveIpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveIpsActionPerformed
        RemoverIP remove = new RemoverIP(gerenciador);
        remove.setVisible(true);
    }//GEN-LAST:event_RemoveIpsActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdicionarIpGrupo;
    private javax.swing.JMenuItem AdicionarMaquinas;
    private javax.swing.JMenuItem Fechar;
    private javax.swing.JMenuItem MostrarRoteamento;
    private javax.swing.JMenuItem RemoveIps;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
